name: Code quality gate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "GitHub Actions pipeline ready for code quality checks"